const config = {
  lemonsqueezy: {
    plans: [
      {
        variantId: "free_plan",
        name: "Free",
        description: "Basic calendar features for personal use",
        price: 0,
        priceAnchor: 0,
        isMonthly: true,
        isYearly: false,
        features: [
          { name: "Basic calendar management" },
          { name: "Up to 5 events per day" },
          { name: "Basic AI suggestions" },
          { name: "Email notifications" },
          { name: "Mobile app access" },
        ],
      },
      {
        variantId: process.env.NEXT_PUBLIC_LEMONSQUEEZY_PLUS_MONTHLY_VARIANT_ID,
        name: "Plus",
        description: "Enhanced features for productivity enthusiasts",
        price: 9,
        priceAnchor: 9,
        isMonthly: true,
        isYearly: false,
        isFeatured: true,
        features: [
          { name: "Everything in Free" },
          { name: "Unlimited events" },
          { name: "Smart scheduling assistant" },
          { name: "Calendar analytics" },
          { name: "Custom reminders" },
          { name: "Calendar sharing" },
        ],
      },
      {
        variantId: process.env.NEXT_PUBLIC_LEMONSQUEEZY_PLUS_YEARLY_VARIANT_ID,
        name: "Plus",
        description: "Enhanced features for productivity enthusiasts",
        price: 90,
        priceAnchor: 90,
        isMonthly: false,
        isYearly: true,
        isFeatured: true,
        features: [
          { name: "Everything in Free" },
          { name: "Unlimited events" },
          { name: "Smart scheduling assistant" },
          { name: "Calendar analytics" },
          { name: "Custom reminders" },
          { name: "Calendar sharing" },
        ],
      },
      {
        variantId: process.env.NEXT_PUBLIC_LEMONSQUEEZY_PRO_MONTHLY_VARIANT_ID,
        name: "Pro",
        description: "Advanced features for professionals & teams",
        price: 19,
        priceAnchor: 19,
        isMonthly: true,
        isYearly: false,
        features: [
          { name: "Everything in Plus" },
          { name: "Advanced AI scheduling" },
          { name: "API access" },
          { name: "Custom integrations" },
        ],
      },
      {
        variantId: process.env.NEXT_PUBLIC_LEMONSQUEEZY_PRO_YEARLY_VARIANT_ID,
        name: "Pro",
        description: "Advanced features for professionals & teams",
        price: 190,
        priceAnchor: 190,
        isMonthly: false,
        isYearly: true,
        features: [
          { name: "Everything in Plus" },
          { name: "Advanced AI scheduling" },
          { name: "API access" },
          { name: "Custom integrations" },
        ],
      },
    ],
  },
};

module.exports = config;
